CREATE TABLE [zap] (
    [UIDSPMO] NVARCHAR(MAX),
    [IDADDRESS] NVARCHAR(MAX),
    [MPVID] NVARCHAR(MAX),
    [MPUSL] NVARCHAR(MAX),
    [MPROF] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);