CREATE TABLE [flk5] (
    [OT_PER] NVARCHAR(4),
    [MSK_OT] NVARCHAR(2),
    [DOMC_TYPE] NVARCHAR(2),
    [SERIES] NVARCHAR(12),
    [NUMBER] NVARCHAR(20),
    [DATEB] DATE,
    [DATEE] DATE,
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);