CREATE TABLE [entry] (
    [ID] NVARCHAR(MAX),
    [NAME_RUS] NVARCHAR(MAX),
    [NAME_ENG] NVARCHAR(MAX),
    [PARENT] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);