CREATE TABLE [zap] (
    [ID_gr] NVARCHAR(MAX),
    [DS_gr] NVARCHAR(MAX),
    [ID_St] NVARCHAR(MAX),
    [ID_T] NVARCHAR(MAX),
    [ID_N] NVARCHAR(MAX),
    [ID_M] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);