CREATE TABLE [zap] (
    [ID_R_I] NVARCHAR(MAX),
    [ID_Igh] NVARCHAR(MAX),
    [KOD_R_I] NVARCHAR(MAX),
    [R_I_NAME] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);