CREATE TABLE [zap] (
    [ID_ZAP] NVARCHAR(MAX),
    [CODE_SH] NVARCHAR(MAX),
    [ID_LEKP] NVARCHAR(MAX),
    [LEKP_EXT] NVARCHAR(MAX),
    [ID_LEKP_EXT] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);