CREATE TABLE [zap] (
    [TER] NVARCHAR(MAX),
    [KOD1] NVARCHAR(MAX),
    [KOD2] NVARCHAR(MAX),
    [KOD3] NVARCHAR(MAX),
    [RAZDEL] NVARCHAR(MAX),
    [NAME1] NVARCHAR(MAX),
    [CENTRUM] NVARCHAR(MAX),
    [NOMDESCR] NVARCHAR(MAX),
    [NOMAKT] NVARCHAR(MAX),
    [STATUS] NVARCHAR(MAX),
    [DATEUTV] NVARCHAR(MAX),
    [DATEVVED] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);