CREATE TABLE [dvn] (
    [CODE_DVN] NVARCHAR(15),
    [CODE_USL] NVARCHAR(15),
    [SEX] NVARCHAR(2),
    [VOZR_DISP] NVARCHAR(2),
    [KOEFF_DVN] DECIMAL(6, 4),
    [NEW_DVN] NVARCHAR(1),
    [TYPE_USL] NVARCHAR(1),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);