CREATE TABLE [erm] (
    [UMO] NVARCHAR(11),
    [OGRN] NVARCHAR(13),
    [ADRES_SP] NVARCHAR(250),
    [PODR] NVARCHAR(17),
    [PODR_ER] NVARCHAR(17),
    [NAME_PODR] NVARCHAR(250),
    [DBEG] DATE,
    [DEND] DATE,
    [MOFID] NVARCHAR(35),
    [MODEPID] NVARCHAR(45),
    [TYPE_OTD] NVARCHAR(1),
    [VID_OTD] NVARCHAR(4),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);