CREATE TABLE [zap] (
    [KOD_TF] NVARCHAR(MAX),
    [KOD_OKATO] NVARCHAR(MAX),
    [SUBNAME] NVARCHAR(MAX),
    [OKRUG] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);