CREATE TABLE [zap] (
    [IDADDRESS] NVARCHAR(MAX),
    [UIDMO] NVARCHAR(MAX),
    [UIDSPMO] NVARCHAR(MAX),
    [N_DOC] NVARCHAR(MAX),
    [ADDR] NVARCHAR(MAX),
    [ADDR_GAR] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);