CREATE TABLE [hmp] (
    [VID_HMP] NVARCHAR(12),
    [N_GR] INT,
    [METOD_HMP] INT,
    [CODE_USL] NVARCHAR(15),
    [PROF_P17] NVARCHAR(2),
    [NAME_P17] NVARCHAR(80),
    [PROFIL] NVARCHAR(30),
    [PROFIL_K] NVARCHAR(30),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);