CREATE TABLE [zap] (
    [ID_M_D] NVARCHAR(MAX),
    [DS_Mrf] NVARCHAR(MAX),
    [ID_Mrf] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);