CREATE TABLE [zap] (
    [ID_CONS] NVARCHAR(MAX),
    [CONS_NAME] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);