CREATE TABLE [zap] (
    [KOD] NVARCHAR(MAX),
    [NAME11] NVARCHAR(MAX),
    [NAME12] NVARCHAR(MAX),
    [ALFA2] NVARCHAR(MAX),
    [ALFA3] NVARCHAR(MAX),
    [NOMDESCR] NVARCHAR(MAX),
    [NOMAKT] NVARCHAR(MAX),
    [STATUS] NVARCHAR(MAX),
    [DATEUTV] NVARCHAR(MAX),
    [DATEVVED] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);