CREATE TABLE [zap] (
    [ID_TEST] NVARCHAR(MAX),
    [ID_EL] NVARCHAR(MAX),
    [DESC_TEST] NVARCHAR(MAX),
    [NSI_OBJ] NVARCHAR(MAX),
    [NSI_EL] NVARCHAR(MAX),
    [USL_TEST] NVARCHAR(MAX),
    [VAL_EL] NVARCHAR(MAX),
    [COMMENT] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [TYPE_MD_TYPE_D] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);