CREATE TABLE [smo] (
    [REGION] NVARCHAR(8),
    [CODE_SMO] NVARCHAR(2),
    [NAME_SMO] NVARCHAR(250),
    [STATUS] BIT,
    [OGRN] NVARCHAR(13),
    [SMOCOD] NVARCHAR(5),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);