EXEC sp_rename 'nsi.dbo.f002.juraddress_index_j', 'juraddress-index_j', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.juraddress_addr_j', 'juraddress-addr_j', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.pstaddress_index_f', 'pstaddress-index_f', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.pstaddress_addr_f', 'pstaddress-addr_f', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.licenziy_n_doc', 'licenziy-n_doc', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.licenziy_d_start', 'licenziy-d_start', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.licenziy_date_e', 'licenziy-date_e', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.licenziy_d_term', 'licenziy-d_term', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insinclude_d_begin', 'insinclude-d_begin', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insinclude_d_end', 'insinclude-d_end', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insinclude_name_e', 'insinclude-name_e', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insinclude_nal_p', 'insinclude-nal_p', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insadvice_year_work', 'insadvice-year_work', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insadvice_duved', 'insadvice-duved', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f002.insadvice_kol_zl', 'insadvice-kol_zl', 'COLUMN'

EXEC sp_rename 'nsi.dbo.f003.juraddress_index_j', 'juraddress-index_j', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f003.juraddress_addr_j', 'juraddress-addr_j', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f003.medinclude_d_begin', 'medinclude-d_begin', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f003.medinclude_d_end', 'medinclude-d_end', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f003.medinclude_name_e', 'medinclude-name_e', 'COLUMN'
EXEC sp_rename 'nsi.dbo.f003.medadvice_year_work', 'medadvice-year_work', 'COLUMN'

EXEC sp_rename 'nsi.dbo.v016.dtrule_rule', 'dtrule-rule', 'COLUMN'
EXEC sp_rename 'nsi.dbo.q023.type_md_type_d', 'type_md-type_d', 'COLUMN'