CREATE TABLE [cgr] (
    [CODE_USL] NVARCHAR(15),
    [PROFIL_K] INT,
    [MKB] NVARCHAR(6),
    [GR_PLAN] NVARCHAR(3),
    [CODE_NOM1] NVARCHAR(15),
    [MCOD_OUT] NVARCHAR(6),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);