CREATE TABLE [dvs] (
    [TER_ST] NVARCHAR(5),
    [R_NAME] NVARCHAR(250),
    [SMOCOD] NVARCHAR(5),
    [SERIES] NVARCHAR(3),
    [NUM_B] NVARCHAR(6),
    [NUM_E] NVARCHAR(6),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);