CREATE TABLE [exq] (
    [TF_OKATO] NVARCHAR(5),
    [N_EXPERT] NVARCHAR(7),
    [IDMSP] INT,
    [VERS] NVARCHAR(4),
    [FAM] NVARCHAR(40),
    [IM] NVARCHAR(40),
    [OT] NVARCHAR(40),
    [SNILS] NVARCHAR(14),
    [DATE_IN] DATE,
    [DATE_OUT] DATE,
    [DATE_K] DATE,
    [ID_GIS] NVARCHAR(11),
    [PROFIL] NVARCHAR(20),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);