CREATE TABLE [zap] (
    [UIDSPMO] NVARCHAR(MAX),
    [IDSPMO] NVARCHAR(MAX),
    [NAM_SPMO] NVARCHAR(MAX),
    [NAM_SK_SPMO] NVARCHAR(MAX),
    [PHONE] NVARCHAR(MAX),
    [OSP] NVARCHAR(MAX),
    [VID_SPMO] NVARCHAR(MAX),
    [OID_SPMO] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);