CREATE TABLE [zap] (
    [IDMO] NVARCHAR(MAX),
    [OID_MO] NVARCHAR(MAX),
    [MCOD] NVARCHAR(MAX),
    [UIDMO] NVARCHAR(MAX),
    [FAM_RUK] NVARCHAR(MAX),
    [IM_RUK] NVARCHAR(MAX),
    [OT_RUK] NVARCHAR(MAX),
    [TYPE_RUK] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);