CREATE TABLE [zap] (
    [UIDEKMP] NVARCHAR(MAX),
    [IDEKMP] NVARCHAR(MAX),
    [N_EXPERT] NVARCHAR(MAX),
    [OKTMO_P] NVARCHAR(MAX),
    [SUBJ] NVARCHAR(MAX),
    [D_BEGIN] NVARCHAR(MAX),
    [D_END] NVARCHAR(MAX),
    [NAME_E] NVARCHAR(MAX),
    [EKS] NVARCHAR(MAX),
    [ZSL] NVARCHAR(MAX),
    [KMO] NVARCHAR(MAX),
    [ZAK] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);