CREATE TABLE [flk2] (
    [DISP] NVARCHAR(3),
    [CODE_USL] NVARCHAR(15),
    [SEX] NVARCHAR(2),
    [VOZR] NVARCHAR(150),
    [P_CEL] NVARCHAR(3),
    [RES_GOSP] NVARCHAR(150),
    [ISH_MOV] NVARCHAR(150),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);