CREATE TABLE [gdg] (
    [CODE_USL] NVARCHAR(15),
    [USL_OK] INT,
    [MKB] NVARCHAR(6),
    [MKB2] NVARCHAR(6),
    [MKB3] NVARCHAR(6),
    [CODE_OPER] NVARCHAR(15),
    [VOZG] NVARCHAR(1),
    [SEX] NVARCHAR(2),
    [DURATION] NVARCHAR(1),
    [DKK] NVARCHAR(15),
    [CODE_OPER2] NVARCHAR(15),
    [FRAC] NVARCHAR(10),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);