CREATE TABLE [gdk] (
    [CODE_USL] NVARCHAR(15),
    [DKK1] NVARCHAR(15),
    [DKK4] NVARCHAR(10),
    [KSLP] NVARCHAR(2),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);