CREATE TABLE [entry] (
    [ID] NVARCHAR(MAX),
    [RZN] NVARCHAR(MAX),
    [PARENT] NVARCHAR(MAX),
    [NAME] NVARCHAR(MAX),
    [ACTUAL] NVARCHAR(MAX),
    [EXISTENCE_NPA] NVARCHAR(MAX),
    [ORDER] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);