CREATE TABLE [entry] (
    [ID] NVARCHAR(MAX),
    [FULLNAME] NVARCHAR(MAX),
    [SHORTNAME] NVARCHAR(MAX),
    [PRINTNAME] NVARCHAR(MAX),
    [MEASUREMENT] NVARCHAR(MAX),
    [UCUM] NVARCHAR(MAX),
    [COEFFICIENT] NVARCHAR(MAX),
    [FORMULA] NVARCHAR(MAX),
    [CONVERSION_ID] NVARCHAR(MAX),
    [CONVERSION_NAME] NVARCHAR(MAX),
    [OKEI_CODE] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);