CREATE TABLE [zap] (
    [ID_St] NVARCHAR(MAX),
    [DS_St] NVARCHAR(MAX),
    [KOD_St] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);