CREATE TABLE [zap] (
    [ID_T] NVARCHAR(MAX),
    [DS_T] NVARCHAR(MAX),
    [KOD_T] NVARCHAR(MAX),
    [T_NAME] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);