CREATE TABLE [zap] (
    [ID_N] NVARCHAR(MAX),
    [DS_N] NVARCHAR(MAX),
    [KOD_N] NVARCHAR(MAX),
    [N_NAME] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);