CREATE TABLE [npr] (
    [OT_PER] NVARCHAR(4),
    [MCOD_IN] NVARCHAR(6),
    [MCOD_OUT] NVARCHAR(6),
    [ENP] NVARCHAR(16),
    [NPOLIC] NVARCHAR(20),
    [SPOLIC] NVARCHAR(10),
    [NOM_NPR] NVARCHAR(20),
    [VID_NPR] NVARCHAR(20),
    [DATE_NPR] DATE,
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);