CREATE TABLE [sbr] (
    [TYPE_NAME] NVARCHAR(250),
    [TYPE_OBJ] NVARCHAR(10),
    [CODE_OBJ] NVARCHAR(3),
    [NAME_OBJ] NVARCHAR(250),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);