CREATE TABLE [zap] (
    [IDHM] NVARCHAR(MAX),
    [HMNAME] NVARCHAR(MAX),
    [DIAG] NVARCHAR(MAX),
    [HVID] NVARCHAR(MAX),
    [HGR] NVARCHAR(MAX),
    [HMODP] NVARCHAR(MAX),
    [IDMODP] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);