CREATE TABLE [zap] (
    [IDSPEC] NVARCHAR(MAX),
    [SPECNAME] NVARCHAR(MAX),
    [POSTNAME] NVARCHAR(MAX),
    [IDPOST_MZ] NVARCHAR(MAX),
    [DATEBEG] NVARCHAR(MAX),
    [DATEEND] NVARCHAR(MAX),
    [OT_PER_Y] NVARCHAR(2),
    [OT_PER_M] NVARCHAR(2),
    [OT_PER_N] NVARCHAR(4)
);