-- создание таблицы c
create table [c] (
	[ot_per] nvarchar(4),
	[code_lpu] nvarchar(6),
	[msk_ot] nvarchar(2),
	[perscode] nvarchar(15),
	[nhistory] nvarchar(20),
	[profil] decimal(3,0),
	[mkb1] nvarchar(6),
	[code_md] nvarchar(6),
	[code_usl] nvarchar(15),
	[date_in] date,
	[date_out] date,
	[ds1_t] decimal(1,0),
	[stad] decimal(4,0),
	[onk_t] decimal(5,0),
	[onk_n] decimal(5,0),
	[onk_m] decimal(5,0),
	[mtstz] decimal(1,0),
	[prot] decimal(1,0),
	[d_prot] date,
	[napr_date] date,
	[napr_v] decimal(1,0),
	[met_issl] decimal(1,0),
	[napr_usl] nvarchar(15),
	[pr_cons] decimal(1,0),
	[usl_tip] decimal(1,0),
	[hir_tip] decimal(1,0),
	[lek_tip_l] decimal(1,0),
	[lek_tip_v] decimal(1,0),
	[luch_tip] decimal(1,0),
	[sod] decimal(7,2),
	[ds1_f] decimal(1,0),
	[dt_cons] date,
	[b_prot] decimal(1,0),
	[k_fr] decimal(2,0),
	[wei] decimal(5,1),
	[hei] decimal(3,0),
	[bsa] decimal(4,2),
	[pptr] decimal(1,0),
	[code_sh] nvarchar(10),
	[vid_vme] nvarchar(15),
	[num_cons] nvarchar(10),
	[idonksl] nvarchar(10)
);


-- создание таблицы ca
create table [ca] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [idonksl] nvarchar(10),
    [diag_tip] decimal(1, 0),
    [diag_code] decimal(3, 0),
    [diag_rslt] decimal(3, 0),
    [diag_date] date,
    [rec_rslt] decimal(1, 0)
);

-- создание таблицы cb
create table [cb] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [idonksl] nvarchar(10),
    [regnum] nvarchar(6),
    [code_sh] nvarchar(10),
    [regnum_dop] nvarchar(25),
    [date_inj] date,
    [kv_inj] decimal(12, 3),
    [kiz_inj] decimal(12, 3),
    [s_inj] decimal(16, 6),
    [sv_inj] decimal(16, 2),
    [siz_inj] decimal(16, 2),
    [red_inj] nvarchar(1)
);

-- создание таблицы d
create table [d] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [mpcod] nvarchar(8),
    [podr] nvarchar(17),
    [code_md] nvarchar(6),
    [fio_md] nvarchar(50),
    [kateg_md] nvarchar(2),
    [spec_md] nvarchar(10),
    [post_md] nvarchar(10),
    [md_ss] nvarchar(14),
    [prvs] decimal(4, 0)
);

-- создание таблицы g
create table [g] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [vid_sf] nvarchar(2),
    [vid_mp] decimal(4, 0),
    [usl_ok] decimal(1, 0),
    [nhistory] nvarchar(20),
    [profil] decimal(3, 0),
    [mkb1] nvarchar(6),
    [mkb2] nvarchar(6),
    [mkb3] nvarchar(6),
    [code_usl] nvarchar(15),
    [code_otd] nvarchar(12),
    [code_md] nvarchar(6),
    [date_in] date,
    [date_out] date,
    [kol_fact] decimal(3, 0),
    [ish_mov] decimal(3, 0),
    [res_gosp] decimal(3, 0),
    [sum_rub] decimal(10, 2),
    [code_nom1] nvarchar(15),
    [code_nom2] nvarchar(15),
    [code_nom3] nvarchar(15),
    [extr] decimal(1, 0),
    [vid_tr] nvarchar(2),
    [sp_case] decimal(1, 0),
    [kz] decimal(10, 5),
    [kus] decimal(6, 2),
    [ku] decimal(6, 4),
    [kslp] decimal(7, 5),
    [kps] decimal(4, 2),
    [vb_p] decimal(1, 0),
    [kd] decimal(6, 4),
    [kdzp] decimal(7, 5),
    [profil_k] decimal(3, 0),
    [p_per] decimal(1, 0),
    [dkk1] nvarchar(15),
    [dkk2] nvarchar(10),
    [dkk3] nvarchar(10),
    [z_sl1] decimal(7, 5),
    [z_sl2] decimal(7, 5),
    [z_sl3] decimal(7, 5),
    [z_sl4] decimal(7, 5),
    [k_sl1] nvarchar(3),
    [k_sl2] nvarchar(3),
    [k_sl3] nvarchar(3),
    [k_sl4] nvarchar(3),
    [dkk4] nvarchar(10),
    [kgp] nvarchar(4)
);

-- создание таблицы i
create table [i] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [nhistory] nvarchar(20),
    [profil] decimal(3, 0),
    [mkb1] nvarchar(6),
    [code_md] nvarchar(6),
    [code_usl] nvarchar(15),
    [date_in] date,
    [date_out] date,
    [date_med] date,
    [meddev] nvarchar(6),
    [number_ser] nvarchar(100)
);

-- создание таблицы k
create table [k] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [vid_mp] decimal(4, 0),
    [usl_ok] decimal(1, 0),
    [vid_sf] nvarchar(2),
    [vid_koeff] nvarchar(2),
    [val_koeff] decimal(12, 8)
);

-- создание таблицы m
create table [m] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [nhistory] nvarchar(20),
    [code_kpmu] nvarchar(15),
    [code_usl] nvarchar(15),
    [date_dvn] date,
    [isp_dvn] nvarchar(2),
    [new_dvn] nvarchar(1),
    [type] nvarchar(1)
);

-- создание таблицы n
create table [n] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [nhistory] nvarchar(20),
    [profil] decimal(3, 0),
    [code_usl] nvarchar(15),
    [mkb1] nvarchar(6),
    [date_in] date,
    [date_out] date,
    [disp] nvarchar(3),
    [vbr] decimal(1, 0),
    [rslt_d] decimal(2, 0),
    [ds1_pr] decimal(1, 0),
    [pr_d_n] decimal(1, 0),
    [ds2_pr] decimal(1, 0),
    [pr_ds2_n] decimal(1, 0),
    [naz_r] decimal(2, 0),
    [naz_sp] decimal(4, 0),
    [naz_v] decimal(1, 0),
    [naz_pmp] decimal(3, 0),
    [naz_pk] decimal(3, 0)
);

-- создание таблицы p
create table [p] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [enp] nvarchar(16),
    [domc_type] nvarchar(2),
    [series] nvarchar(12),
    [number] nvarchar(20),
    [code_msk] nvarchar(5),
    [name_msk] nvarchar(250),
    [okato_ins] nvarchar(8),
    [fam] nvarchar(40),
    [im] nvarchar(40),
    [ot] nvarchar(40),
    [birthday] date,
    [sex] nvarchar(2),
    [okato_nas] nvarchar(11),
    [country] nvarchar(3),
    [pasp_ser] nvarchar(10),
    [pasp_num] nvarchar(12),
    [pasp_vid] nvarchar(2),
    [fam1] nvarchar(40),
    [im1] nvarchar(40),
    [ot1] nvarchar(40),
    [sex_p] nvarchar(2),
    [birthday_p] date,
    [pasp_ser_p] nvarchar(10),
    [pasp_num_p] nvarchar(12),
    [pasp_vid_p] nvarchar(2),
    [mr] nvarchar(100),
    [novor] nvarchar(9),
    [os_sluch] decimal(1, 0),
    [snils] nvarchar(14),
    [vnov] decimal(4, 0),
    [dost_fio] decimal(1, 0),
    [dost_fio_d] decimal(1, 0),
    [dost_dr] decimal(1, 0),
    [vnov_m] decimal(4, 0),
    [pr_lg] nvarchar(2),
    [docdate] date,
    [docorg] nvarchar(100),
    [idrqstdate] date
);

-- создание таблицы u
create table [u] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [mpcod] nvarchar(8),
    [podr] nvarchar(17),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [vid_mp] decimal(4, 0),
    [usl_ok] decimal(1, 0),
    [nhistory] nvarchar(20),
    [profil] decimal(3, 0),
    [mkb1] nvarchar(6),
    [mkb2] nvarchar(6),
    [mkb3] nvarchar(6),
    [code_usl] nvarchar(15),
    [code_md] nvarchar(6),
    [date_in] date,
    [date_out] date,
    [kol_usl] decimal(6, 0),
    [kol_fact] decimal(3, 0),
    [res_gosp] decimal(3, 0),
    [ish_mov] decimal(3, 0),
    [vid_sf] nvarchar(2),
    [tarif_b] decimal(10, 2),
    [tarif_s] decimal(10, 2),
    [tarif_d] decimal(10, 2),
    [sum_rub] decimal(10, 2),
    [vid_tr] nvarchar(2),
    [extr] decimal(1, 0),
    [code_otd] nvarchar(12),
    [souf] decimal(1, 0),
    [med_area] nvarchar(15),
    [tal_hmp] nvarchar(17),
    [date_hmp] date,
    [inv] decimal(1, 0),
    [mcod_out] nvarchar(6),
    [nom_npr] nvarchar(20),
    [date_npr] date,
    [for_pom] decimal(1, 0),
    [mse] decimal(1, 0),
    [p_cel] nvarchar(3),
    [mkb0] nvarchar(6),
    [dn] decimal(1, 0),
    [tal_p] date,
    [ds_onk] decimal(1, 0),
    [c_zab] decimal(1, 0),
    [profil_k] decimal(3, 0),
    [napr_mo] nvarchar(6),
    [ot_per_u] nvarchar(4),
    [idcase] nvarchar(11),
    [scase] nvarchar(2)
);

-- создание таблицы x
create table [x] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [nhistory] nvarchar(20),
    [code_usl] nvarchar(15),
    [date_in] date,
    [date_out] date,
    [time_fix] nvarchar(4),
    [time_in] nvarchar(4),
    [time_out] nvarchar(4),
    [date_fix] date
);

-- создание таблицы y
create table [y] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [nhistory] nvarchar(20),
    [profil] decimal(3, 0),
    [mkb1] nvarchar(6),
    [code_md] nvarchar(6),
    [code_usl] nvarchar(15),
    [date_in] date,
    [date_out] date,
    [wei] decimal(3, 0),
    [data_inj] date,
    [code_sh] nvarchar(5),
    [regnum] nvarchar(6),
    [cod_mark] nvarchar(100),
    [ed_izm] nvarchar(3),
    [dose_inj] decimal(8, 2),
    [method_inj] nvarchar(3),
    [col_inj] decimal(5, 0)
);

-- создание таблицы z
create table [z] (
    [ot_per] nvarchar(4),
    [code_lpu] nvarchar(6),
    [msk_ot] nvarchar(2),
    [perscode] nvarchar(15),
    [nhistory] nvarchar(20),
    [code_usl] nvarchar(15),
    [date_out] date,
    [teeth_code] nvarchar(3),
    [occlusion] nvarchar(1)
);

